[package]
name = "goodbye_dpi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.42", features = ["full"] }
rand = "0.8"
aho-corasick = "1.1"
log = "0.4"
env_logger = "0.11"
