buffer_size: 4096
dns:
  server: cloudflare
  over: https
default: 
  url: "tcp://127.0.0.1:8080"
  blacklist: "default_blacklist"
servers:
- url: "socks5://127.0.0.1:9050"
  blacklist: "tor_blacklist"
